version: '3' 
services:
  flask_app_1: #name of container
    build: ./flask1
    ports:
      - "5001:5000"
    volumes:
      - ./flask1:/app
  flask_app_2:
    build: ./flask2
    ports:
      - "5002:5000"
    volumes:
      - ./flask2:/app



#Docker compose is for running multiple apps and containers simultaneously
    
# services: include the containers 
# build: specifies the folder to the app that will be built
# ports: specified expose ports (<host-port>:<container-port>)
# volumes: allow changes to be detected and then pushes those changes


#Docker Compose Commands
# To build images: docker-compose build
# To run containers: docker-compose up -d
# To stop containers: docker-compose down
# To list containers: docker-compose ps
# To remove containers: docker-compose rm
# To remove volumes: docker-compose down -v
# To delete all: docker-compose down -v --rmi all --remove-orphans